#!/bin/sh
adduser \
    --home=/var/lib/magnetgraph \
    --disabled-password \
    --disabled-login \
    --system \
    magnetgraph
addgroup --system magnetgraph
systemctl daemon-reload
systemctl enable --now magnetgraph.service